[package]
name = "rustCalculator"
version = "0.1.0"
authors = ["eliotb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
nalgebra = "0.20.0"
rand = "0.7.3"
kiss3d = "0.23.0"


